
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123456
  host: localhost

development:
  <<: *default
  database: social_network_development

test:
  <<: *default
  database: social_network_test

production:
  <<: *default
  database: social_network_production
  username: social_network
  password: <%= ENV['SOCIAL_NETWORK_DATABASE_PASSWORD'] %>
